# Fonte
font_family FiraCode Nerd Font Mono
font_size 12


#Outros
disable_ligatures no
enable_audio_bell no

shell zsh
shell_integration_ disabled

url_style curly

remember_window_size no
initial_window_width 640
initial_window_height 480
window_padding_width 30
cursor_blink_interval 0.5

# Tema (cores)
# One Dark by Giuseppe Cesarano, https://github.com/GiuseppeCesarano
# This work is licensed under the terms of the GPL-2.0 license.
# For a copy, see https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html.

background #0D0D0D
foreground #E6E6E6

cursor #707070
cursor_text_color #0D0D0D

selection_background #333333
selection_foreground #FFFFFF

# Preto
color0 #1A1A1A
color8 #2A2A2A

# Branco
color7 #E6E6E6
color15 #FFFFFF

# Cursor
cursor_shape block

# Transparência
background_opacity 0.8
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
confirm_os_window_close 0

sync_to_monitor no
