general {
    lock_cmd = loginctl lock-session #avisa ao systemd
    before_sleep_cmd = loginctl lock-session #garante lock antes de suspender
}

listener {
    timeout = 1800
    on-timeout = hyprlock
    on-resume = hyprctl dispatch dpms on
}